import os
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional
from docx import Document
from pptx import Presentation
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from core.config import settings
from core.logger import logger

class DocumentTool:
    """
    Generates professional documents (Word, PPT, PDF) locally.
    """
    
    def __init__(self):
        self.logger = logger
        self.output_dir = settings.UPLOAD_DIR / "generated"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def create_docx(self, title: str, content: str, filename: Optional[str] = None) -> str:
        """Generates a Microsoft Word document."""
        doc = Document()
        doc.add_heading(title, 0)
        
        # Split content into paragraphs
        for p in content.split("\n\n"):
            doc.add_paragraph(p)
            
        doc.add_paragraph(f"\nGenerated by Antigravity Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        fname = filename or f"{title.replace(' ', '_')}_{datetime.now().strftime('%H%M%S')}.docx"
        fpath = self.output_dir / fname
        doc.save(str(fpath))
        self.logger.info(f"📄 [DOC_GEN] Created Word doc: {fpath}")
        return str(fpath)

    def create_pptx(self, title: str, slides_content: List[Dict[str, str]], filename: Optional[str] = None) -> str:
        """Generates a Microsoft PowerPoint presentation."""
        prs = Presentation()
        
        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = f"Generated Presentation\n{datetime.now().strftime('%Y-%m-%d')}"
        
        # Content Slides
        for s_data in slides_content:
            bullet_slide_layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(bullet_slide_layout)
            slide.shapes.title.text = s_data.get("title", "Untitled Slide")
            slide.placeholders[1].text = s_data.get("content", "")
            
        fname = filename or f"{title.replace(' ', '_')}_{datetime.now().strftime('%H%M%S')}.pptx"
        fpath = self.output_dir / fname
        prs.save(str(fpath))
        self.logger.info(f"📊 [DOC_GEN] Created PowerPoint: {fpath}")
        return str(fpath)

    def create_pdf(self, title: str, content: str, filename: Optional[str] = None) -> str:
        """Generates a basic PDF document using ReportLab."""
        fname = filename or f"{title.replace(' ', '_')}_{datetime.now().strftime('%H%M%S')}.pdf"
        fpath = self.output_dir / fname
        
        c = canvas.Canvas(str(fpath), pagesize=letter)
        width, height = letter
        
        # Basic layout
        c.setFont("Helvetica-Bold", 16)
        c.drawString(72, height - 72, title)
        
        c.setFont("Helvetica", 12)
        y = height - 100
        for line in content.split("\n"):
            if y < 72: # New page
                c.showPage()
                y = height - 72
                c.setFont("Helvetica", 12)
            c.drawString(72, y, line)
            y -= 15
            
        c.save()
        self.logger.info(f"📕 [DOC_GEN] Created PDF: {fpath}")
        return str(fpath)

# Singleton
document_tool = DocumentTool()
