import os
import logging

logger = logging.getLogger(__name__)

# Dynamically resolve backend root -> tools_custom
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CUSTOM_TOOLS_DIR = os.path.join(BASE_DIR, "tools_custom")

class AgenticToolBuilder:
    """
    Enables the Local AI to permanently code its own capabilities.
    If the AI is asked to "create a tool for X", it writes a .py file and drops it here.
    """
    def __init__(self):
        os.makedirs(CUSTOM_TOOLS_DIR, exist_ok=True)
        # Create an __init__.py so python treats it as a module
        init_file = os.path.join(CUSTOM_TOOLS_DIR, "__init__.py")
        if not os.path.exists(init_file):
            with open(init_file, "w") as f:
                f.write("# Auto-generated module for Agentic Tools\n")
                
        logger.info(f"🔨 [TOOL BUILDER] Initialized. Custom Extensions path: {CUSTOM_TOOLS_DIR}")

    def create_persistent_tool(self, tool_name: str, code: str, overwrite: bool = False) -> str:
        """
        Takes python source code generated by the LLM and writes it permanently into tools_custom/.
        """
        if not tool_name.endswith(".py"):
            tool_name += ".py"
            
        safe_name = tool_name.replace(" ", "_").lower()
        file_path = os.path.join(CUSTOM_TOOLS_DIR, safe_name)
        
        if os.path.exists(file_path) and not overwrite:
            return f"❌ Tool '{safe_name}' already exists. Use overwrite=True if intended."
        
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)
            logger.info(f"✅ [TOOL BUILDER] Sucessfully wrote permanent python tool to {file_path}")
            return f"SUCCESS: Capability '{safe_name}' has been permanently integrated into the system."
        except Exception as e:
            logger.error(f"❌ [TOOL BUILDER] Failed to create tool {safe_name}: {e}")
            return f"FAILED: System could not write the tool due to an IO error: {e}"

tool_builder = AgenticToolBuilder()
